[package]
name = "mises-key"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Mises Keys"

[lib]
name = "mises_key"

[dependencies]
# Cryptography
ed25519-dalek = { version = "2.2", default-features = false, features = [
  "alloc",
] }
slip10 = { version = "0.4", default-features = false, features = [] }

# Error Handling
thiserror = { version = "2.0", default-features = false }

# Encodings
bip32 = { version = "0.5", default-features = false, features = [
  "secp256k1",
  "alloc",
] }
bip39 = { version = "2.2", default-features = false, features = [] }
crc32fast = { version = "1.5", default-features = false, features = [] }

# Utils
getrandom = { version = "0.2", default-features = false, optional = true, features = [
] }
zeroize = { version = "1.8", default-features = false, features = [] }


[dev-dependencies]
jsonwebtoken = { version = "9", default-features = false }
serde = { workspace = true, features = ["derive", "alloc"] }
serde_json = { workspace = true, features = ["alloc"] }
tokio = { workspace = true, features = ["macros", "rt"] }
tempfile = "3"

[features]
default = []
std = ["dep:getrandom"]
