// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v3.19.1
// source: mises.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";

export const protobufPackage = "mises";

export interface BootstrapRequest {
  rootGroupName: string;
  ownerName: string;
  deviceName: string;
}

export interface BootstrapResponse {
  rootGroup: string;
  masterKeyCreated: boolean;
  masterKeyPublicKey: string;
  ownerUser: string;
  device: string;
}

function createBaseBootstrapRequest(): BootstrapRequest {
  return { rootGroupName: "", ownerName: "", deviceName: "" };
}

export const BootstrapRequest: MessageFns<BootstrapRequest> = {
  encode(message: BootstrapRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.rootGroupName !== "") {
      writer.uint32(10).string(message.rootGroupName);
    }
    if (message.ownerName !== "") {
      writer.uint32(18).string(message.ownerName);
    }
    if (message.deviceName !== "") {
      writer.uint32(26).string(message.deviceName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BootstrapRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBootstrapRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.rootGroupName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.ownerName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.deviceName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<BootstrapRequest>): BootstrapRequest {
    return BootstrapRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<BootstrapRequest>): BootstrapRequest {
    const message = createBaseBootstrapRequest();
    message.rootGroupName = object.rootGroupName ?? "";
    message.ownerName = object.ownerName ?? "";
    message.deviceName = object.deviceName ?? "";
    return message;
  },
};

function createBaseBootstrapResponse(): BootstrapResponse {
  return { rootGroup: "", masterKeyCreated: false, masterKeyPublicKey: "", ownerUser: "", device: "" };
}

export const BootstrapResponse: MessageFns<BootstrapResponse> = {
  encode(message: BootstrapResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.rootGroup !== "") {
      writer.uint32(10).string(message.rootGroup);
    }
    if (message.masterKeyCreated !== false) {
      writer.uint32(16).bool(message.masterKeyCreated);
    }
    if (message.masterKeyPublicKey !== "") {
      writer.uint32(26).string(message.masterKeyPublicKey);
    }
    if (message.ownerUser !== "") {
      writer.uint32(34).string(message.ownerUser);
    }
    if (message.device !== "") {
      writer.uint32(42).string(message.device);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BootstrapResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBootstrapResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.rootGroup = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.masterKeyCreated = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.masterKeyPublicKey = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.ownerUser = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.device = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<BootstrapResponse>): BootstrapResponse {
    return BootstrapResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<BootstrapResponse>): BootstrapResponse {
    const message = createBaseBootstrapResponse();
    message.rootGroup = object.rootGroup ?? "";
    message.masterKeyCreated = object.masterKeyCreated ?? false;
    message.masterKeyPublicKey = object.masterKeyPublicKey ?? "";
    message.ownerUser = object.ownerUser ?? "";
    message.device = object.device ?? "";
    return message;
  },
};

export type BootstrapServiceDefinition = typeof BootstrapServiceDefinition;
export const BootstrapServiceDefinition = {
  name: "BootstrapService",
  fullName: "mises.BootstrapService",
  methods: {
    bootstrap: {
      name: "Bootstrap",
      requestType: BootstrapRequest,
      requestStream: false,
      responseType: BootstrapResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

export interface BootstrapServiceImplementation<CallContextExt = {}> {
  bootstrap(request: BootstrapRequest, context: CallContext & CallContextExt): Promise<DeepPartial<BootstrapResponse>>;
}

export interface BootstrapServiceClient<CallOptionsExt = {}> {
  bootstrap(request: DeepPartial<BootstrapRequest>, options?: CallOptions & CallOptionsExt): Promise<BootstrapResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
