// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v3.19.1
// source: mises.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";
import { Empty } from "./google/protobuf/empty";

export const protobufPackage = "mises";

export enum Permission {
  ALL = 0,
  CLIENT_ALL = 1,
  CLIENT_CREATE = 2,
  CLIENT_READ = 3,
  CLIENT_UPDATE = 4,
  CLIENT_DELETE = 5,
  USER_ALL = 6,
  USER_CREATE = 7,
  USER_READ = 8,
  USER_UPDATE = 9,
  USER_DELETE = 10,
  UNRECOGNIZED = -1,
}

export interface AuthorizeRequest {
  clientId: string;
  responseType: string;
  responseMode?: string | undefined;
  scope?: string | undefined;
  redirectUri?: string | undefined;
  state?: string | undefined;
  nonce?: string | undefined;
  codeChallenge?: string | undefined;
  codeChallengeMethod?: string | undefined;
}

export interface AuthorizeResponse {
  redirectUri?: string | undefined;
}

export interface TokenRequest {
  authorizationCode?: AuthorizationCode | undefined;
  refreshToken?: RefreshToken | undefined;
  clientCredentials?: ClientCredentials | undefined;
  deviceCode?: DeviceCode | undefined;
  password?: Password | undefined;
  deviceCredentials?: DeviceCredentials | undefined;
}

export interface AuthorizationCode {
  code: string;
  redirectUri?: string | undefined;
  clientId?: string | undefined;
  codeVerifier?: string | undefined;
}

export interface RefreshToken {
  refreshToken: string;
  clientId?: string | undefined;
  scope?: string | undefined;
}

export interface ClientCredentials {
  clientId: string;
  clientSecret: string;
  scope?: string | undefined;
}

export interface DeviceCode {
  deviceCode: string;
  clientId?: string | undefined;
}

export interface Password {
  username: string;
  password: string;
  clientId: string;
  scope?: string | undefined;
}

export interface DeviceCredentials {
  clientId: string;
  scope?: string | undefined;
}

export interface TokenResponse {
  accessToken: string;
  tokenType: string;
  expiresIn?: number | undefined;
  refreshToken?: string | undefined;
  idToken?: string | undefined;
  scope?: string | undefined;
}

export interface DeviceAuthorizeRequest {
  clientId?: string | undefined;
  scope?: string | undefined;
}

export interface DeviceAuthorizeResponse {
  deviceCode: string;
  userCode: string;
  verificationUri: string;
  verificationUriComplete?: string | undefined;
  expiresIn: number;
  interval?: number | undefined;
}

export interface IntrospectRequest {
  token: string;
  tokenTypeHint?: string | undefined;
  clientId?: string | undefined;
  clientSecret?: string | undefined;
}

export interface Claims {
  active: boolean;
  scope?: string | undefined;
  clientId?: string | undefined;
  username?: string | undefined;
  tokenType?: string | undefined;
  exp?: number | undefined;
  iat?: number | undefined;
  nbf?: number | undefined;
  sub?: string | undefined;
  aud?: string | undefined;
  iss?: string | undefined;
  jti?:
    | string
    | undefined;
  /**
   * When an access token delegates authority to another identity this
   * claim contains the delegated identity id (e.g., a graph Identity ID)
   */
  actingFor?: string | undefined;
}

export interface RevokeRequest {
  token: string;
  tokenTypeHint?: string | undefined;
  clientId?: string | undefined;
  clientSecret?: string | undefined;
}

export interface PushedAuthorizeRequest {
  clientId: string;
  responseType?: string | undefined;
  responseMode?: string | undefined;
  scope?: string | undefined;
  redirectUri?: string | undefined;
  state?: string | undefined;
  nonce?: string | undefined;
  codeChallenge?: string | undefined;
  codeChallengeMethod?: string | undefined;
}

export interface PushedAuthorizeResponse {
  requestUri: string;
  expiresIn?: number | undefined;
}

export interface BackchannelAuthRequest {
  clientId?: string | undefined;
  scope?: string | undefined;
  loginHint?: string | undefined;
}

export interface BackchannelAuthResponse {
  authReqId: string;
  expiresIn?: number | undefined;
  interval?: number | undefined;
}

export interface ClientRegisterRequest {
  clientId?: string | undefined;
  name?: string | undefined;
  redirectUris: string[];
  grantTypes: string[];
  responseTypes: string[];
  scope?: string | undefined;
  tokenEndpointAuthMethod?: string | undefined;
  serviceId?: string | undefined;
  requirePkce?: boolean | undefined;
  applicationType?: string | undefined;
  contacts: string[];
  clientUri?: string | undefined;
  logoUri?: string | undefined;
  policyUri?: string | undefined;
  tosUri?: string | undefined;
  jwksUri?: string | undefined;
  jwks?: string | undefined;
  sectorIdentifierUri?: string | undefined;
  subjectType?: string | undefined;
  idTokenSignedResponseAlg?: string | undefined;
  idTokenEncryptedResponseAlg?: string | undefined;
  audience?: string | undefined;
  idTokenEncryptedResponseEnc?: string | undefined;
  userinfoSignedResponseAlg?: string | undefined;
  userinfoEncryptedResponseAlg?: string | undefined;
  userinfoEncryptedResponseEnc?: string | undefined;
  requestObjectSigningAlg?: string | undefined;
  requestObjectEncryptionAlg?: string | undefined;
  requestObjectEncryptionEnc?: string | undefined;
  tokenEndpointAuthSigningAlg?: string | undefined;
  defaultMaxAge?: number | undefined;
  requireAuthTime?: boolean | undefined;
  defaultAcrValues: string[];
  initiateLoginUri?: string | undefined;
  requestUris: string[];
  postLogoutRedirectUris: string[];
  frontchannelLogoutUri?: string | undefined;
  frontchannelLogoutSessionRequired?: boolean | undefined;
  backchannelLogoutUri?: string | undefined;
  backchannelLogoutSessionRequired?: boolean | undefined;
  accessTokenExpiry?: number | undefined;
  refreshTokenExpiry?: number | undefined;
}

export interface NativeAuthenticateRequest {
  /** client id (UUID string) or development shortcut 'tauri' */
  clientId?:
    | string
    | undefined;
  /** optional hint about the subject to act as (server may ignore and create its own) */
  sub?: string | undefined;
  scope?: string | undefined;
}

export interface Client {
  /** UUID string */
  id: string;
  clientId: string;
  clientSecret?: string | undefined;
  name?: string | undefined;
  redirectUris: string[];
  grantTypes: string[];
  responseTypes: string[];
  scope?: string | undefined;
  tokenEndpointAuthMethod?: string | undefined;
  requirePkce?: boolean | undefined;
  applicationType?: string | undefined;
  contacts: string[];
  serviceId?: string | undefined;
  clientUri?: string | undefined;
  logoUri?: string | undefined;
  policyUri?: string | undefined;
  tosUri?: string | undefined;
  jwksUri?: string | undefined;
  jwks?: string | undefined;
  sectorIdentifierUri?: string | undefined;
  subjectType?: string | undefined;
  idTokenSignedResponseAlg?: string | undefined;
  idTokenEncryptedResponseAlg?: string | undefined;
  idTokenEncryptedResponseEnc?: string | undefined;
  userinfoSignedResponseAlg?: string | undefined;
  userinfoEncryptedResponseAlg?: string | undefined;
  userinfoEncryptedResponseEnc?: string | undefined;
  requestObjectSigningAlg?: string | undefined;
  requestObjectEncryptionAlg?: string | undefined;
  requestObjectEncryptionEnc?: string | undefined;
  tokenEndpointAuthSigningAlg?: string | undefined;
  defaultMaxAge?: number | undefined;
  requireAuthTime?: boolean | undefined;
  defaultAcrValues: string[];
  initiateLoginUri?: string | undefined;
  requestUris: string[];
  postLogoutRedirectUris: string[];
  frontchannelLogoutUri?: string | undefined;
  frontchannelLogoutSessionRequired?: boolean | undefined;
  backchannelLogoutUri?: string | undefined;
  backchannelLogoutSessionRequired?: boolean | undefined;
  accessTokenExpiry?: number | undefined;
  refreshTokenExpiry?: number | undefined;
  audience?: string | undefined;
}

export interface EndSessionRequest {
  idTokenHint?: string | undefined;
  postLogoutRedirectUri?: string | undefined;
  state?: string | undefined;
}

export interface EndSessionResponse {
  redirectUri?: string | undefined;
}

export interface UserInfo {
  sub: string;
  permissions: Permission[];
  name?: string | undefined;
  givenName?: string | undefined;
  familyName?: string | undefined;
  preferredUsername?: string | undefined;
  email?: string | undefined;
  emailVerified?: boolean | undefined;
  picture?: string | undefined;
}

export interface OpenIdConfiguration {
  /** Core issuer & endpoints */
  issuer: string;
  authorizationEndpoint?: string | undefined;
  tokenEndpoint?: string | undefined;
  userinfoEndpoint?: string | undefined;
  revocationEndpoint?: string | undefined;
  introspectionEndpoint?: string | undefined;
  jwksUri?: string | undefined;
  registrationEndpoint?:
    | string
    | undefined;
  /** Supported values */
  scopesSupported: string[];
  responseTypesSupported: string[];
  responseModesSupported: string[];
  grantTypesSupported: string[];
  tokenEndpointAuthMethodsSupported: string[];
  tokenEndpointAuthSigningAlgValuesSupported: string[];
  codeChallengeMethodsSupported: string[];
  /** Subject & ID token algorithms */
  subjectTypesSupported: string[];
  idTokenSigningAlgValuesSupported: string[];
  idTokenEncryptionAlgValuesSupported: string[];
  idTokenEncryptionEncValuesSupported: string[];
  /** UserInfo & Request object algs */
  userinfoSigningAlgValuesSupported: string[];
  userinfoEncryptionAlgValuesSupported: string[];
  requestObjectSigningAlgValuesSupported: string[];
  requestObjectEncryptionAlgValuesSupported: string[];
  /** RFC/OIDC metadata */
  serviceDocumentation?: string | undefined;
  claimsSupported: string[];
  claimsLocalesSupported: string[];
  uiLocalesSupported: string[];
  acrValuesSupported: string[];
  /** Feature / boolean flags */
  claimsParameterSupported?: boolean | undefined;
  requestParameterSupported?: boolean | undefined;
  requestUriParameterSupported?: boolean | undefined;
  requireRequestUriRegistration?:
    | boolean
    | undefined;
  /** Policy & legal */
  opPolicyUri?: string | undefined;
  opTosUri?:
    | string
    | undefined;
  /** Session & logout */
  checkSessionIframe?: string | undefined;
  endSessionEndpoint?: string | undefined;
  frontchannelLogoutSupported?: boolean | undefined;
  frontchannelLogoutSessionSupported?: boolean | undefined;
  backchannelLogoutSupported?: boolean | undefined;
  backchannelLogoutSessionSupported?:
    | boolean
    | undefined;
  /** Extensions */
  deviceAuthorizationEndpoint?: string | undefined;
  pushedAuthorizationRequestEndpoint?: string | undefined;
}

export interface Jwk {
  kid: string;
  kty: string;
  use: string;
  alg: string;
  crv: string;
  x: string;
  y: string;
  /** Allowed key operations (e.g., "sign", "verify") */
  keyOps: string[];
}

export interface Jwks {
  keys: Jwk[];
}

export interface Configuration {
  issuer: string;
  deviceId: string;
  serviceId: string;
  clientId: string;
  publicUri?: string | undefined;
}

export interface GetClientRequest {
  clientId: string;
}

export interface IsAllowedForUserRequest {
  clientId: string;
  scope: string;
}

export interface ClientAllowed {
  scope: string;
}

export interface ApproveForUserRequest {
  clientId: string;
}

function createBaseAuthorizeRequest(): AuthorizeRequest {
  return {
    clientId: "",
    responseType: "",
    responseMode: undefined,
    scope: undefined,
    redirectUri: undefined,
    state: undefined,
    nonce: undefined,
    codeChallenge: undefined,
    codeChallengeMethod: undefined,
  };
}

export const AuthorizeRequest: MessageFns<AuthorizeRequest> = {
  encode(message: AuthorizeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clientId !== "") {
      writer.uint32(10).string(message.clientId);
    }
    if (message.responseType !== "") {
      writer.uint32(18).string(message.responseType);
    }
    if (message.responseMode !== undefined) {
      writer.uint32(26).string(message.responseMode);
    }
    if (message.scope !== undefined) {
      writer.uint32(34).string(message.scope);
    }
    if (message.redirectUri !== undefined) {
      writer.uint32(42).string(message.redirectUri);
    }
    if (message.state !== undefined) {
      writer.uint32(50).string(message.state);
    }
    if (message.nonce !== undefined) {
      writer.uint32(58).string(message.nonce);
    }
    if (message.codeChallenge !== undefined) {
      writer.uint32(74).string(message.codeChallenge);
    }
    if (message.codeChallengeMethod !== undefined) {
      writer.uint32(82).string(message.codeChallengeMethod);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AuthorizeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuthorizeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clientId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.responseType = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.responseMode = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.scope = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.redirectUri = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.state = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.nonce = reader.string();
          continue;
        }
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.codeChallenge = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.codeChallengeMethod = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<AuthorizeRequest>): AuthorizeRequest {
    return AuthorizeRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AuthorizeRequest>): AuthorizeRequest {
    const message = createBaseAuthorizeRequest();
    message.clientId = object.clientId ?? "";
    message.responseType = object.responseType ?? "";
    message.responseMode = object.responseMode ?? undefined;
    message.scope = object.scope ?? undefined;
    message.redirectUri = object.redirectUri ?? undefined;
    message.state = object.state ?? undefined;
    message.nonce = object.nonce ?? undefined;
