[package]
name = "mises-tauri"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
description = "MISES: Mesh Identity and Security Enforcement System Tauri Application"

[lib]
name = "mises_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
# tauri
tauri = { version = "2", default-features = false, features = [
  "common-controls-v6",
  "compression",
  "dynamic-acl",
  "wry",
  "x11",
] }

# async
tokio = { version = "1", default-features = false, features = [
  "rt",
  "net",
  "io-util",
  "fs",
  "process",
  "time",
] }
tokio-util = { version = "0.7", default-features = false, features = [] }
tonic = { version = "0.14", default-features = false, features = ["transport"] }

# networking
bytes = { version = "1", default-features = false }
http = { version = "1", default-features = false }
hyper = { version = "0.14", default-features = false, features = [
  "client",
  "server",
  "tcp",
  "http1",
  "http2",
] }
http-body-util = { version = "0.1", default-features = false }
tower = { version = "0.5", default-features = false }
hyper-util = { version = "0.1", default-features = false, features = ["tokio"] }

# utils
log = { workspace = true }
uuid = { workspace = true, features = ["v7", "std"] }
prost = { version = "0.14", default-features = false }
config = { version = "0.15", default-features = false, features = ["json"] }

# serialization
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = [] }
tauri-plugin-opener = { version = "2", default-features = false, features = [] }
tauri-plugin-log = { version = "2", default-features = false, features = [] }
tauri-plugin-deep-link = { version = "2", default-features = false, features = [
] }
tauri-plugin-cli = { version = "2", default-features = false, features = [] }
native-authentication = { path = "../../../crates/native-authentication", default-features = false, features = [
] }

# workspace
mises-proto = { path = "../../../crates/proto", default-features = false }
mises-file-store = { path = "../../../crates/file-store", default-features = false, features = [
  "std",
] }

[target."cfg(any(target_os = \"macos\", windows, target_os = \"linux\"))".dependencies]
tauri-plugin-single-instance = { version = "2", features = ["deep-link"] }
