[package]
name = "mises-async-kv-bytes"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Mises Async KV Bytes"

[lib]
name = "mises_async_kv_bytes"

[dependencies]
# Async
async-trait = { workspace = true, features = [] }

# Error Handling
thiserror = { version = "2.0", default-features = false }

# Locking
parking_lot = { version = "0.12", optional = true, default-features = false }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }

[features]
default = ["in-memory"]
std = []
in-memory = ["dep:parking_lot"]
