[package]
name = "mises-core"
edition = "2024"
version = "0.1.0"
authors = ["nathanfaucett@gmail.com"]
description = "Mises Core"
license = "MIT OR Apache-2.0"
repository = "https://github.com/aicacia/rs-mises"
rust-version = "1.93"

[lib]
name = "mises_core"

[dependencies]
mises-key = { path = "../key", default-features = false, features = [] }
mises-graph = { path = "../graph", default-features = false }

# utils
log = { version = "0.4", default-features = false, features = [] }
chrono = { version = "0.4", default-features = false, features = [
  "alloc",
  "serde",
  "clock",
] }
uuid = { version = "1.20", default-features = false, features = [
  "v4",
  "serde",
] }

# serialization
serde = { version = "1", default-features = false, features = [
  "derive",
  "alloc",
] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }
base64 = { version = "0.21", default-features = false, features = ["alloc"] }

# async
async-trait = { version = "0.1", default-features = false, features = [] }

[dev-dependencies]
# Use the in-memory repository for core unit tests
mises-graph = { path = "../graph", default-features = false, features = [
  "in-memory",
  "std",
] }

mises-key = { path = "../key", default-features = false, features = ["std"] }

tokio = { version = "1.49", default-features = false, features = [
  "macros",
  "rt",
] }
chrono = { version = "0.4", default-features = false, features = [
  "serde",
  "std",
] }

[features]
# default to no_std; enable std opt-in
default = []
std = ["mises-graph/std"]
