[package]
name = "mises-graph"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Mises Graph"

[lib]
name = "mises_graph"

[dependencies]
# Internal
mises-async-kv-bytes = { path = "../async-kv-bytes", default-features = false }

# Async
async-trait = { workspace = true, features = [] }

# Error Handling
thiserror = { version = "2.0", default-features = false, optional = true }

# Serialization
serde = { workspace = true, features = ["derive", "alloc"] }
serde_json = { workspace = true, features = ["alloc"] }

# Utils
chrono = { workspace = true, features = ["alloc", "serde", "clock"] }
hashbrown = { version = "0.16", default-features = false, features = [
  "default-hasher",
] }
parking_lot = { version = "0.12", optional = true, default-features = false }
uuid = { workspace = true, optional = true, features = ["v4", "v7", "serde"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
chrono = { workspace = true, features = ["serde", "std"] }


[features]
# default to no_std; enable std opt-in
default = ["in-memory"]
uuid = ["dep:uuid"]
std = [
  "mises-async-kv-bytes/std",
  "chrono/std",
  "serde/std",
  "serde_json/std",
  "uuid/std",
]
# in-memory repository feature
in-memory = ["dep:parking_lot", "mises-async-kv-bytes/in-memory"]

# Optional richer error support (enables `thiserror` + `serde_json` helpers)
rich-errors = ["thiserror"]
