[package]
name = "mises-graph"
edition = "2024"
version = "0.1.0"
authors = ["nathanfaucett@gmail.com"]
description = "Mises Graph"
license = "MIT OR Apache-2.0"
repository = "https://github.com/aicacia/rs-mises"
rust-version = "1.93"

[lib]
name = "mises_graph"

[dependencies]
# internal
mises-async-kv-bytes = { path = "../async-kv-bytes", default-features = false }

# Utils
uuid = { workspace = true, optional = true, features = ["v4", "v7", "serde"] }
hashbrown = { version = "0.16", default-features = false, features = [
  "default-hasher",
] }

# Serialization
serde = { workspace = true, features = ["derive", "alloc"] }
serde_json = { workspace = true, features = ["alloc"] }

# Utils
chrono = { workspace = true, features = ["alloc", "serde", "clock"] }
async-trait = { workspace = true, features = [] }
parking_lot = { version = "0.12", optional = true, default-features = false }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
chrono = { workspace = true, features = ["serde", "std"] }


[features]
# default to no_std; enable std opt-in
default = ["in-memory"]
uuid = ["dep:uuid"]
std = [
  "mises-async-kv-bytes/std",
  "chrono/std",
  "serde/std",
  "serde_json/std",
  "uuid/std",
]
# in-memory repository feature
in-memory = ["dep:parking_lot", "mises-async-kv-bytes/in-memory"]
