[package]
name = "mises-grpc-server"
edition = "2024"
version = "0.1.0"
authors = ["nathanfaucett@gmail.com"]
description = "Mises gRPC Server"
license = "MIT OR Apache-2.0"
repository = "https://github.com/aicacia/rs-mises"
rust-version = "1.93"

[lib]
name = "mises_grpc_server"

[dependencies]
mises-core = { path = "../core", default-features = false, features = [] }
mises-graph = { path = "../graph", default-features = false, features = [] }
mises-proto = { path = "../proto", default-features = false, features = [] }
mises-async-kv-bytes = { path = "../async-kv-bytes", default-features = false, features = [
] }
mises-key = { path = "../key", default-features = false, features = [] }

# Crypto
jsonwebtoken = { version = "10.3", default-features = false, features = [
  "rust_crypto",
] }
sha2 = { version = "0.10", default-features = false, features = ["std"] }

# Serialization
base64 = { workspace = true, features = [] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["alloc"] }

# Utils
log = { workspace = true, features = ["std"] }
chrono = { workspace = true, features = ["std"] }
getrandom = { workspace = true, features = ["std"] }
url = { version = "2.5", default-features = false, features = ["std"] }
uuid = { workspace = true, features = [] }

# Auth
native-authentication = { path = "../native-authentication", default-features = false, features = [
] }

# gRPC
prost-types = { workspace = true, features = [] }
tonic = { workspace = true, features = [] }


[dev-dependencies]
mises-graph = { path = "../graph", default-features = false, features = [
  "in-memory",
  "std",
] }
tokio = { workspace = true, features = ["macros", "rt"] }

[features]
default = ["file-descriptor-set"]
file-descriptor-set = ["mises-proto/file-descriptor-set"]
