[package]
name = "mises-grpc-server"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Mises gRPC Server"

[lib]
name = "mises_grpc_server"

[dependencies]
# Internal
mises-async-kv-bytes = { path = "../async-kv-bytes", default-features = false, features = [
] }
mises-core = { path = "../core", default-features = false, features = [] }
mises-graph = { path = "../graph", default-features = false, features = [] }
mises-key = { path = "../key", default-features = false, features = [] }
mises-proto = { path = "../proto", default-features = false, features = [] }
native-authentication = { path = "../native-authentication", default-features = false, features = [
] }

# Cryptography
jsonwebtoken = { version = "10.3", default-features = false, features = [
  "rust_crypto",
] }
sha2 = { version = "0.10", default-features = false, features = ["std"] }

# gRPC
prost-types = { workspace = true, features = [] }
tonic = { workspace = true, features = [] }

# Serialization
base64 = { workspace = true, features = [] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["alloc"] }

# Utils
chrono = { workspace = true, features = ["std"] }
getrandom = { workspace = true, features = ["std"] }
log = { workspace = true, features = ["std"] }
url = { version = "2.5", default-features = false, features = ["std"] }
uuid = { workspace = true, default-features = false, features = ["v7", "std"] }


[dev-dependencies]
mises-graph = { path = "../graph", default-features = false, features = [
  "in-memory",
  "std",
] }
tokio = { workspace = true, features = ["macros", "rt"] }

[features]
default = ["std", "file-descriptor-set"]
std = [
  "mises-async-kv-bytes/std",
  "mises-core/std",
  "mises-graph/std",
  "mises-key/std",
  "base64/std",
  "serde/std",
  "serde_json/std",
  "chrono/std",
  "getrandom/std",
  "log/std",
]
file-descriptor-set = ["mises-proto/file-descriptor-set"]
